name: gpudrive
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_5
  - ca-certificates=2023.12.12=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py311h06a4308_0
  - python=3.11.8=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py311h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.41.2=py311h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - build==1.1.1
      - cachecontrol==0.14.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - crashtest==0.4.1
      - cryptography==42.0.5
      - distlib==0.3.8
      - dulwich==0.21.7
      - fastjsonschema==2.19.1
      - filelock==3.13.1
      - idna==3.6
      - importlib-metadata==7.0.2
      - installer==0.7.0
      - jaraco-classes==3.3.1
      - jeepney==0.8.0
      - keyring==24.3.1
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - packaging==23.2
      - pexpect==4.9.0
      - pkginfo==1.10.0
      - platformdirs==4.2.0
      - poetry==1.8.2
      - poetry-core==1.9.0
      - poetry-plugin-export==1.6.0
      - ptyprocess==0.7.0
      - pycparser==2.21
      - pyproject-hooks==1.0.0
      - rapidfuzz==3.6.2
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - secretstorage==3.3.3
      - shellingham==1.5.4
      - tomlkit==0.12.4
      - trove-classifiers==2024.3.3
      - urllib3==2.2.1
      - virtualenv==20.25.1
      - zipp==3.17.0