name: gpudrive
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.13
  - pip=23.3.1
  - python=3.11.8
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2024a
  - wheel=0.41.2
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - build==1.2.1
      - cachecontrol==0.14.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cleo==2.1.0
      - crashtest==0.4.1
      - cryptography==42.0.5
      - distlib==0.3.8
      - dulwich==0.21.7
      - fastjsonschema==2.19.1
      - filelock==3.13.3
      - idna==3.6
      - importlib-metadata==7.1.0
      - installer==0.7.0
      - jaraco-classes==3.4.0
      - jeepney==0.8.0
      - keyring==24.3.1
      - more-itertools==10.2.0
      - msgpack==1.0.8
      - packaging==24.0
      - pexpect==4.9.0
      - pkginfo==1.10.0
      - platformdirs==4.2.0
      - poetry==1.8.2
      - poetry-core==1.9.0
      - poetry-plugin-export==1.7.1
      - ptyprocess==0.7.0
      - pycparser==2.22
      - pyproject-hooks==1.0.0
      - rapidfuzz==3.7.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - secretstorage==3.3.3
      - shellingham==1.5.4
      - stable-baselines3==2.3.2
      - tensorboard
      - tomlkit==0.12.4
      - trove-classifiers==2024.3.25
      - urllib3==2.2.1
      - virtualenv==20.25.1
      - zipp==3.18.1
      - huggingface_hub==0.26.5
      - wandb==0.19.1
      - python-box==7.3.0
      - python-dotenv==1.0.1
      - jax==0.4.0
      - typer==0.9.0
      - matplotlib==3.9
      - pufferlib
      - huggingface_hub
      - jaxlib
